### ISSUE TITLE
Non-human genomes with more than 21+XY chromosomes

### ISSUE THREAD

**Issue by AlainRico** [CenterForMedicalGeneticsGhent/WisecondorX#104]
Great tool.
What are the parameters to change in order to be able to analyse other genomes with more chromosomes than human genome?

**Comment by matthdsm** [comment]
Hi,

Sadly, the human genome configuration is hardcoded into the application, so it's only usable for human samples at the time.

M

**Comment by matthdsm** [comment]
I don't think it's going to be very trivial to make this more flexible. Feel free to browse the code and submit a pr if you find something.

Thanks for your interest in WisecondorX!
