### ISSUE TITLE
Can WisecondorX software be used to evaluate the copy number of genes ？

### ISSUE THREAD

**Issue by zhoudreames** [CenterForMedicalGeneticsGhent/WisecondorX#108]
For our no-human genome, the ADAM6 genes contain 4-6 copies， I want to estimate the copy number of ADAM6 at the population level by using WGS Illumina data. Can I use this software to do it？ thanks~

**Comment by zhoudreames** [comment]
@leraman I am sorry to disturb your, can you help me? Thanks~

**Comment by matthdsm** [comment]
Hi @zhoudreames,

Thank you for your interest in WisecondorX! I'm sorry to say we won't be able to help you, the application is developed for human use only.

Cheers
Matthias
