### ISSUE TITLE
no prediction on chrX (completely gray)

### ISSUE THREAD

**Issue by rgiannico** [CenterForMedicalGeneticsGhent/WisecondorX#13]
Hi leraman, 
For some reason I always find the complete X chromosome to be blacklisted (it's completely grey) in the predict output plot. 
I know this could happen if you use some male fetus samples creating the reference, but I'm using normal female samples only.
I tried using version v0.1.1 and then I tried updating to the most recent v0.2 (converting the npz files with your "fix.convert.npz.py") but nothing changed. 
I tried to build the reference using a subset of my normal female samples (to exclude the chance some training sample could have some problems) but nothing changed. 
Do you have any other suggestion? What might have gone wrong?

**Comment by leraman** [comment]
Hi @rgiannico,
That is weird, I've never experienced this. Would you mind sending me some npz files you've used to create the reference? I'll look in to it.

Best, Lennart

**Comment by rgiannico** [comment]
Ok, thank you for your help! 
You can download 80 normal female training samples .npz files from here: https://drive.google.com/file/d/1eXsz0YvKIxBo3pRUw6rRSZGAtSsozqt3/view?usp=sharing

**Comment by leraman** [comment]
Hi @rgiannico,
Thanks for the files. I've used the last 79 files for the creation of a 1000 kb reference, and used the first one as a test case. The X chromosome seems not to be blacklisted and analysed correctly (attached image).

Are you sure you used the latest version? Bioconda's buffer is full so the latest version is not yet downloadable using conda install. You might need to clone it manually from this github -- if a version issue would indeed be the case. If you are not sure which version your are on, could I see an example of the stdout?

![genome_wide](https://user-images.githubusercontent.com/15171833/42893471-b3659eec-8ab4-11e8-87f2-10f3583d2087.png)

Best, Lennart

**Comment by leraman** [comment]
@rgiannico,

Actually, I just checked and noticed the latest version (v0.2.0) is already conda installable. Maybe a re-run of the install command could do the trick?

Best, Lennart

**Comment by rgiannico** [comment]
Yes, thanks!
I just reinstalled wisecondorx v0.2  (now that the v0.2 is available in conda) in a fresh new conda environment and it works! 
I suppose it was just an installation problem as you pointed out. 
Thank you very much! :)
