### ISSUE TITLE
Sex determination - always F

### ISSUE THREAD

**Issue by BClaire** [CenterForMedicalGeneticsGhent/WisecondorX#14]
Hi,

I recently downloaded the latest release of wisecondorX (v0.2.0) and tried to use it on our data. I followed your suggestion and used bowtie2 and bamsorbamdup for alignment and deduplication. Then I tried to convert the bam files to npz and while the software runs perfectly, I had a problem with  sex determination: I always got females, even if I know that some samples are from male feti (these are control samples that were sequenced and analyzed with another technique some years ago). 
Could you help me understand what the problem is? We have performed an illumina sequencing (paired end, very short reads, very low depth). And as it is the first time I try to analyze such samples (before we were using iontorrent technology), I don't know if the problem is due to the samples of the analyses. 

thanks for your help!

Claire

**Comment by leraman** [comment]
Hi @BClaire,

WisecondorX does not derive fetal gender, but just 'gender'. This is executed since WisecondorX is a tool meant for applications beyond NIPT. As all of your samples are derived from pregnant women, the gender is always returned as female.
For NIPT, you should exclusively use samples from female feti for the creation of the reference, as described in the manual (https://github.com/CenterForMedicalGeneticsGhent/WisecondorX#running-wisecondorx).

**Comment by BClaire** [comment]
Hi,


Thanks for your quick answer! This is indeed perfectly logical and I should have thought about this explanation.

I will go on with the analysis!


Claire



________________________________
De : leraman <notifications@github.com>
Envoyé : mercredi 1 août 2018 09:36
À : CenterForMedicalGeneticsGhent/WisecondorX
Cc : BARDEL DANJEAN CLAIRE; Mention
Objet : Re: [CenterForMedicalGeneticsGhent/WisecondorX] Sex determination - always F (#14)


Hi @BClaire<https://github.com/BClaire>,

WisecondorX does not derive fetal gender, but just 'gender'. This is executed since WisecondorX is a tool meant for applications beyond NIPT. As all of your samples are derived from pregnant women, the gender is always returned as female.
For NIPT, you should exclusively use samples from female feti for the creation of the reference, as described in the manual (https://github.com/CenterForMedicalGeneticsGhent/WisecondorX#running-wisecondorx).

-
