### ISSUE TITLE
Is there a provision for sex chromosome aneuploidies?

### ISSUE THREAD

**Issue by GreeshmaThulasi** [CenterForMedicalGeneticsGhent/WisecondorX#16]
Hi ,
Does WisecondorX having a provision for determining sex chromosome aneuploidies like X0, XXX, XXY, XYY ?
From the bed files and from the plot, I'm able to see whether the fetus is Male or Female (from the gain and loss indications). What about any sex chromosome aneuploidies?
**If the ChrX is coming as constitutional monoploidy(with red dots), does we conclude it as XY or X0?** 

**_what do you mean by constitutional triploidy? (does it mean the whole diploid set is increased into triple set? means, other than 46 chromosomes there will be 69 chromosomes) Is it trisomy rather than triploidy?_**

With Regards,
Greeshma Thulasi

**Comment by GreeshmaThulasi** [comment]
Ok @leraman 
Waiting for the new addition from your side... Thanking you for the current tool.
_In the plot, I've a doubt that, whether its constitutional triploid or trisomy?, constitutional diploid or disomy?, and constitutional monoploidy or monosomy?_

**Comment by leraman** [comment]
Hi @GreeshmaThulasi,

We're currently working on a software that predicts aneuploidies and could aid in retrieving the true source of an observed deviation for NIPT. I'll keep you updated once its published/released.

**Comment by GreeshmaThulasi** [comment]
Hi @leraman ,
Thank you for the hopeful news. Please update at whenever it has done.

**Comment by ArcticGene** [comment]
Hi Dear @leraman
Have you developed any algorithm for detecting SCAs? 
You mentioned that you have some ideas for SCAs detection, if you don't developed anything yet for this, it will be nice to give me a clue to work on.

Thanks.

**Comment by leraman** [comment]
Hi @ArcticGene 

Detecting SCAs is tricky, since maternal/paternal mozaic aberrations often bias results. We have developped a method that indicates whether SCAs are fetal derived, based on the predicted fetal fraction. This is explained in our paper: https://obgyn.onlinelibrary.wiley.com/doi/full/10.1002/pd.5508?af=R

Hope this helps

**Comment by ArcticGene** [comment]
Hi
Thanks Dear @leraman

I took a look at the paper, in the section "**PREFACE indirectly hints towards potential sex aneuploidies**", you said that we can capture the most frequent sex aneuploidies by directly subtracting FFY with FFX, independent from gender, I looked for the FFY value in the PREFACE.R file, but nothing found, just a comment.
How can I get the FFY value to do further analysis?
What is the cutoff for the final calculated value?

Can we determine the exact aneuploidy (XO, XXX, XXY, XYY) based on the final calculated value? or just we can say that there may be an aneuploidy?

Would you please add a piece of code to the PREFACE to determine SCAs optionally?
Or much better if add an optional feature for determining the sex of multiple pregnancies.

As you mentioned in the paper PREFACE is able to determine SCAs and the sex of multiple pregnancies, it will be very nice if you add these features to the code too.

Best
AG
