### ISSUE TITLE
custom plot colors

### ISSUE THREAD

**Issue by przemekl** [CenterForMedicalGeneticsGhent/WisecondorX#22]
Have you considered the possibility of allowing users to define colors on the chart (plotter.R; color.A and B) as a command line parameters?

**Comment by leraman** [comment]
Hi @przemekl 

This will not be implemented. Anyway, if you prefer other colors, feel free to adapt the RGB values at https://github.com/CenterForMedicalGeneticsGhent/WisecondorX/blob/master/wisecondorX/include/plotter.R#L105 locally.

**Comment by przemekl** [comment]
OK, thanks.
