### ISSUE TITLE
mapping quality filter

### ISSUE THREAD

**Issue by rgiannico** [CenterForMedicalGeneticsGhent/WisecondorX#23]
Hi @leraman ,
I see you suggest to use the following bowtie2 command line to get the bam file. 
`bowtie2 --local -p n --fast-local -x index -U input | bamsormadup inputformat=sam threads=n SO=coordinate outputformat=bam indexfilename=sample.bam.bai > sample.bam`

And you also specify that 
> [...] it is very important that **no** read quality filtering is executed prior the running WisecondorX [...]

But It seems to me you do not suggest any mapping quality filter. I mean something like this:
`samtools view -q 10 -b aln.bam > aln.uniq.bam` 

Filtering out reads with mapping quality <10 will exclude reads mapping over multiple positions. 
Is there a specific reason why you do not use this filter? Do you suggest to use it for NIPT or not?

**Comment by leraman** [comment]
Hi @rgiannico 

Indeed, filtering should not be executed.

WisecondorX uses low quality reads to recognize e.g. repeats. If you filter these out, the 'newref' phase will not be able to accurately annotate these loci. You could try this rather liberal MAPQ10 filter and compare the results, but generally, I would not recommend it.
