### ISSUE TITLE
plotter.R Unable to start device PNG

### ISSUE THREAD

**Issue by rmvpaeme** [CenterForMedicalGeneticsGhent/WisecondorX#28]
If anyone else should have the same problem, when running WisecondorX predict on a cluster, I got the error

```
Error in .External2(C_X11, paste0("png::", filename), g$width, g$height,  :
  unable to start device PNG
Calls: png
Execution halted
```

The solution was to add `options(bitmapType='cairo')` to the header of `plotter.R`

**Comment by leraman** [comment]
Hi @rmvpaeme 

Thanks for the suggestion! Will look into this.

Cheers, Lennart
