### ISSUE TITLE
Choice of bin sizes in NPZ conversion and reference building

### ISSUE THREAD

**Issue by tdido** [CenterForMedicalGeneticsGhent/WisecondorX#36]
The README file indicates that during BAM to NPZ conversion "the reference bin size should be a multiple of this value".

I was hoping if you could shed some light on how the two bin sizes interact, in order to be able to decide what values to use.

**Comment by leraman** [comment]
The bin size of the BAM to NPZ conversion does not impact the final profiles. The resolution of a resulting profile is entirely dependent on the bin size of the reference.
However, the bin size during the conversion phase sets the efficiency of that process, but evidently, converted files with a bin size of 200 kb cannot be used to create a 100 kb reference. In practice, I would keep the default value of 5 kb during conversion. This enables you to create references of 5, 10, 15, 20kb, etc. For e.g. a coverage of 0.25, you're probably looking for a 100 kb reference.

**Comment by tdido** [comment]
That's very clear. Thank you!
