### ISSUE TITLE
run 10 reference samples has infinite value in result_r

### ISSUE THREAD

**Issue by zsanli** [CenterForMedicalGeneticsGhent/WisecondorX#37]
[INFO - 2019-03-28 08:08:06]: Executing circular binary segmentation ...
Error in parse_con(txt, bigint_as_char) :
  lexical error: invalid char in json text.
          813008, 0.35726431002764203, Infinity, 0.2661991523863737, 0
                                   (right here) ------^
Calls: read_json ... parse_json -> parse_and_simplify -> parseJSON -> parse_con
Execution halted
[CRITICAL - 2019-03-28 08:08:08]: Rscript failed: Command '['Rscript', '/usr/local/lib/python3.6/site-packages/wisecondorX/include/CBS.R', '--infile', '/S1_CBS_tmp_01.json']' returned non-zero exit status 1.

how can I find exclude blacklist?

Many thanks.

**Comment by matthdsm** [comment]
Hi,

Can you please elaborate on your issue, include the command and executable version. If possible, also provide some sample data.

Thanks
M

**Comment by zsanli** [comment]
Dear Matthias,
I would like to call back my issue as I increased the number of reference samples to 25 and test 1 sample and it create the result. I think the previous issue is because either not enough reference sample or not balanced on gender. Many thanks for your reply so quickly.

all best

zhi

**Comment by leraman** [comment]
Hi @zsanli,

Glad it works! Could you share your version with us anyway?

Best, Lennart

**Comment by zsanli** [comment]
hi,
I use pip install -U git+
https://github.com/CenterForMedicalGeneticsGhent/WisecondorX
setup.py show 1.1.0

zhi

leraman <notifications@github.com> 于2019年3月29日周五 下午12:53写道：
