### ISSUE TITLE
Difference with consensus from other CNV callers

### ISSUE THREAD

**Issue by tdido** [CenterForMedicalGeneticsGhent/WisecondorX#38]
I have a pipeline which uses QDNAseq and CTRL-freec (it used to include other tools, but since results were highly overlapping I eventually reduced it to these two).

I'm testing WisecondorX, since I much prefer the way it's implemented. I ran some samples I usually use for comparisons, and I found that there are certain differences specific to WisecodorX (see images at the bottom). In particular, there's a huge area that comes up as over-represented in WCX, even if very slightly.

I'd really appreciate any tips to help me understand whether I should consider the WisecondorX result as more accurate, or if it may be related to some parameters that I could adjust.

My samples are FFPE, ~1.5x, aligned as suggested in the README, ref bin size 85k, 22 healthy samples for ref. All other parameters default.

Running v1.0.2, latest available in bioconda.

1. CTRL-freec
![freec](https://user-images.githubusercontent.com/1568319/55155166-fcb0e700-5156-11e9-8bb1-82642654eaf5.png)
2. QDNAseq
![qdna](https://user-images.githubusercontent.com/1568319/55155273-3550c080-5157-11e9-9996-1c84ba5d478e.png)
3. WisecondorX
![wcx](https://user-images.githubusercontent.com/1568319/55155278-371a8400-5157-11e9-9671-524d97bec881.png)

Thanks!

**Comment by leraman** [comment]
Hi @tdido,

With < v1.0.3, an important consideration is the choice of `--beta`.  Default, this value is pretty liberal: small ratio differences are seen as aberrant (which generally works great for NIPT). However, from > v1.1.0 (released today) on, aberration calling relies on z-scores (default in v1.1.0), which is often better for research, and will return more accurate results for your non-NIPT application.

You can download the latest version using:
```
pip install -U git+https://github.com/CenterForMedicalGeneticsGhent/WisecondorX
```

Let me know if this increases overlap with the other tools.

Best, Lennart

**Comment by tdido** [comment]
That sounds great. Are you planning to put 1.1.0 on bioconda? My pipelines are set up to automatically create conda environments, and that would be a big help.

**Comment by leraman** [comment]
It will be soon: https://github.com/bioconda/bioconda-recipes/pull/14226

**Comment by tdido** [comment]
I've run my test samples again, and indeed the default parameters in v1.1.0 give me a better agreement. Also great to know about --beta for tuning it further. Attaching the new output, for reference.

Thanks!

![chr13](https://user-images.githubusercontent.com/1568319/55323378-3a777d80-547f-11e9-82c8-f049ada4fabc.png)
