### ISSUE TITLE
how to set up the running strategy in real diagnosis and productive enviroment

### ISSUE THREAD

**Issue by zsanli** [CenterForMedicalGeneticsGhent/WisecondorX#41]
hello,
who can tell me if I use this this tool in a diagnosis lab how I set up the running strategy in real diagnosis and productive environment. e.g. I run 100 health samples first, then create reference npz, then every week I have 50 test samples to test, and always to predict it with reference npz, do I need run and add more health samples every week and create new reference npz?

zhi

**Comment by leraman** [comment]
Hi @zsanli 

As long if there are no changes introduced to your experimental protocol and computational pipeline (e.g. mapping), you can use the same reference. There is no need to add samples.

Best, Lennart
