### ISSUE TITLE
comparison with illumina veriseq

### ISSUE THREAD

**Issue by zsanli** [CenterForMedicalGeneticsGhent/WisecondorX#43]
Dear Author,
What is the comparison with illumina veriseq commercial product if I use WisecondorX in production? What algorithm of veriseq used? Many thanks.

zhi

**Comment by matthdsm** [comment]
Hi @zsanli 

First and foremost, ours if free!
All joking aside, we'll have to take a look at the (limited) information available of the veriseq software to make a comparison.
A quick scan of the available docs makes me think the analysis software if very specifically geared towards use in concordance with their VeriSeq prep kit. WiseCondorX should be able to handle data from just about any kit, provided you have enough samples available to build a good reference.

My colleague @leraman will be able to provide you with more specific information when he's back from holidays.

Cheers
M

@leraman 
for reference
- [SE version ](https://www.illumina.com/content/dam/illumina-marketing/documents/products/datasheets/veriseq-nipt-analysis-software-16-samples-data-sheet-1000000016709-00.pdf)
- [PE version ](https://www.illumina.com/content/dam/illumina-marketing/documents/products/datasheets/veriseq-nipt-analysis-software-48-samples-data-sheet-1000000028276.pdf)

**Comment by zsanli** [comment]
Dear Matthias,
	Many thanks for your quick email. I am looking forward for information from your colleagues.

Have a nice day 

zhi

**Comment by leraman** [comment]
Hi @zsanli 

I'm not aware of the Veriseq algorithms: the files provided by @matthdsm will be of more help than I would. If you're wondering which of both software performs best in combination with your settup, I would recommend you to perform a small comparative study, including some confirmed positive and negative results.

Best, Lennart

**Comment by zsanli** [comment]
Dear Leraman,
	Many thanks for your suggestion.

All best

zhi
