### ISSUE TITLE
Running Stage (3) Predict CNAs error

### ISSUE THREAD

**Issue by chaizuolin** [CenterForMedicalGeneticsGhent/WisecondorX#44]
Hello:
     I.m running Predict CNAs error,error message:
         [INFO - 2019-05-08 13:09:43]: Starting CNA prediction
[INFO - 2019-05-08 13:09:43]: Importing data ...
[INFO - 2019-05-08 13:09:43]: Normalizing autosomes ...
[INFO - 2019-05-08 13:09:45]: Normalizing gonosomes ...
[INFO - 2019-05-08 13:09:46]: Executing circular binary segmentation ...
Error in parse_con(txt, bigint_as_char) : 
  lexical error: invalid char in json text.
          74074074, 1.383087732503899, Infinity, 1.4173424149169755, 1
                     (right here) ------^
Calls: read_json ... parse_json -> parse_and_simplify -> parseJSON -> parse_con
停止执行
[CRITICAL - 2019-05-08 13:09:46]: Rscript failed: Command '['Rscript', '/root/anaconda2/lib/python2.7/site-packages/wisecondorX/include/CBS.R', '--infile', '/share/chaizuolin/03_WorkTest/WisecondorX-master/19041515-YCD_out_CBS_tmp_01.json']' returned non-zero exit status 1
       How do I need to change it,thank you

**Comment by leraman** [comment]
Hi @chaizuolin 

Which version are you using? How many samples (males/females) are including in your reference?

**Comment by chaizuolin** [comment]
Hello@

> 嗨@chaizuolin
> 
> 你使用的是哪个版本？您的参考中包含多少样本（男性/女性）？

Hello@leraman
        I'm using the latest version,Use twelve negative samples to create a reference

**Comment by leraman** [comment]
Including more reference samples (if possible) will probably resolve this issue, as it did for issue #37. Make sure that the amount of males/females are more or less balanced.

**Comment by chaizuolin** [comment]
First of all, thank you very much for your reply.


I'll try what you say.I hope you can solve my problem,Thank you again.





------------------ 原始邮件 ------------------
发件人: "leraman"<notifications@github.com>; 
发送时间: 2019年5月8日(星期三) 下午3:46
收件人: "CenterForMedicalGeneticsGhent/WisecondorX"<WisecondorX@noreply.github.com>; 
抄送: "夜枫"<732110213@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [CenterForMedicalGeneticsGhent/WisecondorX] Running Stage (3)Predict CNAs error (#44)




Including more reference samples (if possible) will probably resolve this issue, as it did for issue #37. Make sure that the amount of males/females are more or less balanced.
 
&mdash;
