### ISSUE TITLE
why the ratio and zscore are NaN??

### ISSUE THREAD

**Issue by chaijinchao** [CenterForMedicalGeneticsGhent/WisecondorX#52]
hi,
          i run the WisecondorX, but many regions are NaN in bins.bed file.  There are some reads mapped in these regions, and i want to know why the ratio and zscore are NaN?

**Comment by leraman** [comment]
NaN's represent loci of 'underterminable' copy number: https://github.com/CenterForMedicalGeneticsGhent/WisecondorX#id_binsbed

You can make locus blacklisting less stringent, using the --maskrepeats option, but results will be less reliable: https://github.com/CenterForMedicalGeneticsGhent/WisecondorX#stage-3-predict-copy-number-alterations

**Comment by chaijinchao** [comment]
Thank you for your suggestions, i set the --maskrepeats option as 0, but the ratio and zscore in these regions are still NaNs, and the copy number of these regions are ‘LOSS’ using SNP-array.

**Comment by leraman** [comment]
Hi, @chaijinchao 

That's possible, if your samples have insufficient reads in these loci, or when these bins are extremely variable. There is no point in retrieving copy number when the data cannot be trusted.

Hopes this helps.
