### ISSUE TITLE
Some questions about WisecondorX newref 

### ISSUE THREAD

**Issue by LiQingsolab** [CenterForMedicalGeneticsGhent/WisecondorX#53]
Hi,

When I used WisecondorX newref  to combine my reference sample, I got this err: 

/Path/bin/Anaconda2/bin/WisecondorX newref /sxyf_keyan/01.yanfa/01.sWGS_1908/24.sWGS.cnv/01.sWGS_Cut_20200514/00.ref/test_REF_2/*npz  reference.50k.npz --binsize 50000 --cpus 8

Traceback (most recent call last):
  File "/Path/02.SoftData/bin/Anaconda2/bin/WisecondorX", line 12, in <module>
    sys.exit(main())
  File "/Path/02.SoftData/bin/Anaconda2/lib/python2.7/site-packages/wisecondorX/main.py", line 371, in main
    args.func(args)
  File "/Path/02.SoftData/bin/Anaconda2/lib/python2.7/site-packages/wisecondorX/main.py", line 55, in tool_newref
    genders, trained_cutoff = train_gender_model(samples)
  File "/Path/02.SoftData/bin/Anaconda2/lib/python2.7/site-packages/wisecondorX/newref_tools.py", line 46, in train_gender_model
    cut_off = gmm_x[local_min_i][0]
IndexError: index 0 is out of bounds for axis 0 with size 0

I can't find the reason, when I used some sample.npz do this part, I can got the finish result, but when I used another samples.npz, I would get this err. 

So, What can I do to deal with this proble?

**Comment by leraman** [comment]
Hi,

This error indicates that WisecondorX fails to separate male from female samples. You have a few options:
- I'm guessing you are not on the latest version (you can update using pip install, see manual), which should be more robust against this error.
- Include as much samples as possible in your reference.
- If you are working with NIPT samples, be sure to include the --NIPT flag.
- Avoid references that exclusive contain same-gender samples (all male/all female). WiseconcorX will fail to correctly normalize X & Y in this case.

Hope this helps.

**Comment by LiQingsolab** [comment]
Dear leraman, 

Thanks very much for your reply !

I try to update this software to the latest version, and used 50 male samples and 48 female samples but I still got that err,  so, how many gender samples are appropriate for my aims or  what's appropriate gender ratio? 

Thanks again!

**Comment by leraman** [comment]
Hi @LiQingsolab 

100 samples should suffice. Can you confirm that you are using the latest version? The error shouldn't be exactly the same, as `cut_off = gmm_x[local_min_i][0]` is not on line 46 in the latest version, as your error stated. Otherwise this might be a bug which I'll look into.

Best, Lennart

**Comment by LiQingsolab** [comment]
Dear leraman,

Thanks again for your reply !

1)  I check the version of my softerware, I think I got the latest version, and "cut_off = gmm_x[local_min_i][0]" is on line 49:
############################################
33     # import matplotlib.pyplot as plt
34     # fig, ax = plt.subplots(figsize=(10, 6))
35     # ax.hist(y_fractions, bins=50, normed=True)
36     # ax.plot(gmm_x, gmm_y, 'r-', label='Gaussian mixture fit')
37     # ax.set_xlim([0.001, 0.01])
38     # ax.legend(loc='best')
39     # plt.show()
40
41     if yfrac is not None:
42         cut_off = yfrac
43     else:
44         sort_idd = np.argsort(gmm_x)
45         sorted_gmm_y = gmm_y[sort_idd]
46
47         local_min_i = argrelextrema(sorted_gmm_y, np.less)
48
49         cut_off = gmm_x[local_min_i][0]
50
51     genders[y_fractions > cut_off] = 'M'
52     genders[y_fractions < cut_off] = 'F'
53
54     return genders.tolist(), cut_off
#######################################################

2)  I try to use different number of samples to creat Ref, for example, 53 male samples and 86 female samples or  48 male samples and 50 female samples, but each test all got the same err: 
###########################
Traceback (most recent call last):
  File "/path//anaconda2/bin/WisecondorX", line 10, in <module>
    sys.exit(main())
  File "/path/anaconda2/lib/python2.7/site-packages/wisecondorX/main.py", line 400, in main
    args.func(args)
  File "/path/anaconda2/lib/python2.7/site-packages/wisecondorX/main.py", line 61, in tool_newref
    genders, trained_cutoff = train_gender_model(samples, args.yfrac)
  File "/path/anaconda2/lib/python2.7/site-packages/wisecondorX/newref_tools.py", line 49, in train_gender_model
    cut_off = gmm_x[local_min_i][0]
IndexError: index 0 is out of bounds for axis 0 with size 0
#####################

3) I decided to ignore the sex chromsome result and used "--yfrac 1 " parameter, and  got a good result.  So, I want to ask another question:
a. Can I get the result in different Chromosome arm, like the result of  "*_chr_statistics.txt"
b. How to get a appropriate threshold to filter aberrations result ( "aberrations.bed") 

Thanks for your attention and Thanks  again !

**Comment by leraman** [comment]
Setting the parameter `--yfrac` indeed circumvents the need to train a gender model. Answering your new questions:
- a. I'm not sure what you intend. You mean instead of chromosome-level, arm-level statistics? Unfortunatly no, but you can always generate your own based on the bins en segments files.
- b. I would say it depends on the quality of the normalization (and thus the size of the reference set). You have two options: using `--beta` (sets linear cutoff based on the purity of the sample) or using `--zscore` (this is recommended when using large reference sets)

**Comment by leraman** [comment]
Would you mind sharing a set of .npz files that generate the original problem (via mail), so I can reproduce and push a fix?

**Comment by LiQingsolab** [comment]
Hi @leraman,

Thanks for your reply!

I have read your paper and find a appropriate method to calculate the arm-level CNA. You have done a great job, It has provided us with a lot of help.

And about sharing the .npz files, I'm so sorry about this, these data were produced by our coopertator, I'm just one of the analysts, I can't share these data. I'm so sorry!

Thanks again for your help.

**Comment by leraman** [comment]
I understand, no problem. Glad you found a solution!

Best
