### ISSUE TITLE
Segment Zscore calculation

### ISSUE THREAD

**Issue by ChadFibke** [CenterForMedicalGeneticsGhent/WisecondorX#54]
Hey @leraman,

I've read the WisecondorX paper (and started looking into the code), and was wondering if you could elaborate on the Segmental Zscore calculation?

![Zscore_segment](https://user-images.githubusercontent.com/31668367/83078497-9c555800-a02e-11ea-804c-cd42486c10fc.png)

Are the Segment ratios of interest (Rn, R...,Rm) simply the: log2( Target bin corrected read value / median (corrected read value of all within sample reference bins)?

Also I was curious about how the r ratios (r1,n, r1,..., r1,m) are calculated. Are they log2( Reference bin corrected read value / median(corrected read value of all reference bins at this loci from the reference samples)? 

I'm sorry in advance if this has an obvious answer! 

Best,
Chad

**Comment by leraman** [comment]
Hi @ChadFibke 

'R' indeed represents corrected read values, using within sample reference bins. However, these values are median centered by substracted the median R, instead of dividing. The same goes for 'r', which is the same measure, yet for 'reference samples' instead of the 'sample of interest'.

Hope this helps

**Comment by ChadFibke** [comment]
Hey @leraman,

I'm still a little confused. 

> However, these values are median centered by substracted the median R, instead of dividing.

As in log2( Target bin corrected read value **-** median (corrected read value of all within sample reference bins)?

> μw() calculates the average of the provided sequence weighted by bin-wise variability calculated during reference creation. 

Is this simply weighting by the variability at a given bin across all reference samples

> The same goes for 'r', which is the same measure, yet for 'reference samples' instead of the 'sample of interest'.

I'm not sure I understand how you get the underlying distribution to calculate the the r ratio. Would it be using the reference index for each bin to see how each reference sample's target been deviates for the reference samples "within-sample" reference bins? 

 Would you be able to provide a dummy example for these calculation?

Best,
Chad

**Comment by leraman** [comment]
Hi @ChadFibke 

I'll try to explain what happens in steps.

First we need a **reference** to normalize new cases. Say we use 100 healthy reference samples; and default parameters: a bin size of 100 kb, where every bin is given 300 'within-sample' reference bins. With respect to your question, two importance steps happen:
- (1) Each bin is assigned 300 other bins (located all across the genome). These are selected according to the reference samples: using these, we can statistically define a set of 300 bins that 'acts alike' the current bin. These links are saved and will be used to calculate ratios at the 'predict' stage.
- (2) Next, for each reference sample, the ratio ('r') of its bins are calculated using 'number of reads at current bin'/'the mean number of reads at corresponding 300 reference bins' (and log2-transformed). Once all ratios of a sample are derived, the values are median centered within that samples. These values are finally saved in a matrix (columns bins; rows reference samples) and will be used to calculate z-scores at the 'predict' stage.

Next we **predict** a new sample using previous reference.
- The ratios are calculated using (1): for each bin, its 300 within-sample reference bins are known (derived in previous stage), using the same formula: 'number of reads at current bin'/'the mean number of reads at reference bins' (+ log2-transformation and median centering).
- The ratio of a **segment** (stretch of **bins**) is now defined as the mean ratio of its bins, but weighted by variability at each bin (the variability can be retrieved from (2), using the standard deviation). These ratios, given we know the location of the segments of the sample of interest following circular binary segmentation, are also derived for every reference sample.
- Now, you can easily calculate a standard Z-score for each segment: ('ratio of segment of sample of interest' - 'mean ratio of same segment across reference samples')/'standard deviation of same segment across reference samples'.

Hope this helps.

Best, Lennart

**Comment by ChadFibke** [comment]
Hey @leraman,

This explanation cleared everything up! I appreciate the support, and am excited to start using WisecondorX  :)

Best,
Chad
