### ISSUE TITLE
Unable to run the predict command

### ISSUE THREAD

**Issue by GreeshmaThulasi** [CenterForMedicalGeneticsGhent/WisecondorX#56]
Hi,
I was able to generate the plot and bed files using the predict function. Suddenly my Ubuntu system is crashed and now I'm using a VirtualBox to run Ubuntu.
I'm able to convert BAM to .npz file. But while giving predict command, getting the error like,
![Screenshot from 2020-07-14 17-05-06](https://user-images.githubusercontent.com/28426342/87421207-32037180-c5f4-11ea-8871-d6d2c66a4616.png)

Please help me to resolve the problem.

Thanks in advance
Greeshma Thulasi

**Comment by leraman** [comment]
I'm guessing your file reference_output.npz isn't actually a reference file but a convert file?

Best

**Comment by GreeshmaThulasi** [comment]
Hi,
I'm using the same reference file (reference_output.npz) from the beginning itself and it executed without any error.

**Comment by leraman** [comment]
You have probably created your reference file using an older version of WisecondorX. In this case have two options:
- Downgrade WisecondorX
- Create a new reference (preferred)

Best, Lennart
