### ISSUE TITLE
How to get reference_input_dir/*.npz file

### ISSUE THREAD

**Issue by xiaotiqingzz** [CenterForMedicalGeneticsGhent/WisecondorX#57]
Hi, how can I get the reference_input_dir/*.npz? 
```
Stage (2) Create reference
WisecondorX newref reference_input_dir/*.npz reference_output.npz [--optional arguments]
```

**Comment by xiaotiqingzz** [comment]
reference_input_dir/*.npz Download from somewhere or other software change .fasta to .npz?

**Comment by leraman** [comment]
The reference is not created from fasta files, but from a series of healthy reference samples, which you can create using stage 1.

Best
