### ISSUE TITLE
Question: different depth of the same sample have different result

### ISSUE THREAD

**Issue by LiQingsolab** [CenterForMedicalGeneticsGhent/WisecondorX#60]
Dear,

WisecondorX plays a great role in our project. Recently, we found a problem when we used WisecondorX to analysis sWGS data:
Different batches of the same sample (different depth) had different result, I tryed to found the regulation of  the distribution of depths, in fact they have similar  patterns , but why the result(**._bins.bed、**_chr_statistics.txt) were so different?

I am looking forward for your reply! 
Thanks again!

Qing

**Comment by leraman** [comment]
Hi @LiQingsolab 

My apologies for the late response. What do you mean by 'different'; can you post an example?

Best, Lennart
