### ISSUE TITLE
Number of normal/reference samples to run WisecondorX

### ISSUE THREAD

**Issue by twinnystarz** [CenterForMedicalGeneticsGhent/WisecondorX#62]
Hi,

Running Wisecondor for the first time, how many normal/reference samples would you recommend to use for normalization?

Thank you.

Kind regards,
T

**Comment by leraman** [comment]
Hi @twinnystarz 

You'll likely find your answer here: https://github.com/CenterForMedicalGeneticsGhent/WisecondorX#running-wisecondorx

Best, Lennart

**Comment by twinnystarz** [comment]
Thank you so much @lennart!
