### ISSUE TITLE
Determine y fraction cutoff

### ISSUE THREAD

**Issue by KhanhLPBao** [CenterForMedicalGeneticsGhent/WisecondorX#65]
Hi, I'm just new to bioinformatics and trying WisecondorX for treatment with my fastq data. On the making reference there is --yfrac command that I have to type. My sample contain both male and female and I have search but cannot find anyway to determine Y read fraction cutoff. How can you calculate the fraction cutoff for making reference?

**Comment by leraman** [comment]
Hi @KhanhLPBao 

An option (`--plotyfrac`) for plotting the yfrac has been added to the newest release

release:
https://github.com/CenterForMedicalGeneticsGhent/WisecondorX/releases/tag/v1.2.0

`--plotyfrac`:
https://github.com/CenterForMedicalGeneticsGhent/WisecondorX#stage-2-create-reference
