### ISSUE TITLE
WisecondorX prediction identify gender of all samples are female

### ISSUE THREAD

**Issue by KhanhLPBao** [CenterForMedicalGeneticsGhent/WisecondorX#70]
I'm working with the references of 90 samples with the number of male and female is approximately equal. WisecondorX can correctly reidentify all genders from the reference files and guest the gender of sample files. However, after analysis the statistics I find out that all gender on the statistic file are all female and when I use --gender M to correct the gender this text appeared before it calculate:

> [WARNING - 2021-01-14 06:30:30]: This sample is male, whilst the reference is created with fewer than 5 males. The female gonosomal reference will be used for X predictions. Note that these might not be accurate. If the latter is desired, create a new reference and include more male samples.

Does anyone know why this error happened?

**Comment by leraman** [comment]
Hi @KhanhLPBao 

Are you using NIPT samples? If so, do not forget to include the --nipt flag during reference creation (https://github.com/CenterForMedicalGeneticsGhent/WisecondorX/#stage-2-create-reference)

**Comment by leraman** [comment]
The gender provided by the statistics file returns the 'gender of the used reference', which is in case of NIPT always female. It might make more sense to change this to the predicted gender. I'll make changes accordingly.

**Comment by KhanhLPBao** [comment]
Hi @leraman 
I just download and install the 1.2.1 version of WisecondorX you posted. The notification was gone but the output its looks like the same. The plot and .bed file not shown any chromosome Y on male sample. My reference file contained 202 samples (110 males and 92 females), the command I use to make reference was:
`WisecondorX newref /path/to/ref/*.npz 202samples.npz --nipt --cpu5`
 The gender prediction made by `WisecondorX gender` returned 100% correction with the gender report from the sequencer. I don't know if there is something about reference bins of chromosome Y's bins or by something else. I have attatched the reference file and 2 samples on the link below (I'm sorry its too heavy to attach):
https://drive.google.com/file/d/1lcpTA3-59lY6da8_B7GdYpi5zqd3AY_G/view?usp=sharing

**Comment by leraman** [comment]
Hi @KhanhLPBao 

Y chromosomes are never shown when using a NIPT reference. It is impossible to infer a 'normal state' for Y, since Y levels always depend on the fetal fraction.

**Comment by KhanhLPBao** [comment]
Hi @leraman 
So does I need to make another 2 separated reference files for male and female? Because from what I see in all male samples the program returned a result of losing 1 chromosome X (because male chromosome is XY). Or any solution to fix this problem?

**Comment by leraman** [comment]
Hi @KhanhLPBao 

This is normal behaviour. You only need one NIPT reference. It is not possible to normalize the Y chromosome, since the expected Y level depends on the fetal fraction, which is not known by WisecondorX. The drop in X for male fetuses is again expected; it reflects the fetal fraction and is actually used by PREFACE to calculate FFX.

Concerning your last question, I'm guessing you are refering to the response variable 'FFY' (or any other measure that reflects the fetal fraction)? There is no code provided to calculate this measure, since there are a lot of different approaches, most of which are fairly easy to implement.
