### ISSUE TITLE
Question about CNV detection

### ISSUE THREAD

**Issue by bnouyou** [CenterForMedicalGeneticsGhent/WisecondorX#72]
Hello,

I would like to know if this is possible to use WisecondorX for CNV detection on WES data. And, in that case, what is the minimal size of CNV. I suppose this depends of the reference size. But do you have suggestions for creating the reference ?

Thank you in advance for your help.

**Comment by leraman** [comment]
Hi @bnouyou 

WisecondorX is developped to be most accurate with sWGS data, but I have seen some very decent results on WES. I would try a 100 kb reference; if the quality of the profiles seem suboptimal, try increasing the reference bin size.

**Comment by bnouyou** [comment]
Hi @leraman 

I have quite good results on 'big' CNV (more than 300 kb) using a reference bin size of 100 kb.
But I would like to detect smaller CNV and here, they are not detected. I will try with smaller reference bin size. I suppose if I use a reference bin zise of 10 kb, I should see smaller CNV, right ?

I have a question : in the bed file 'segments', when I look for the postion of the CNV I am looking for (known CNV), I see that some contiguous segments have a very negative Z-score (in case of a deletion), so I am wondering, how work the tool for deciding if there is actually a deletion or not? How many contiguous segments are taken fro the decision?

Thank you.

**Comment by leraman** [comment]
Sure, you can try a 10 kb ref (it will take some time to generate). Your noise levels will increase however, so there is a limit, depending on your sequencing depth, to how small a reference can get.

I'm not sure what you mean with your last question, but you'll likely find your answer in de WisecondorX paper.

**Comment by bnouyou** [comment]
Sorry, I will try to make a better explanation for my last question.

In the output files, there is a file called '_bins.bed'. Here I can see the zscores of all bins of the sample.
My question is here, if there are some consecutive bins with a very negative zscore, how can we consider that there is a deletion ? 
On some cases, I don't see anything reported in the '_aberration.bed' file. But when I am looking in the 'bins.bed' file, I see that there are some consegutive bins with very negative zscore. I know that there is a deletion there for this sample, so I am wondering why the algorithm hasn't reported it in the 'aberration.bed' file. Should I need to change another parameter, maybe in the function 'predict' ? Currently I have let the default parameters.

**Comment by leraman** [comment]
Aberrations are called based on the _segments.bed file and not the _bins.bed file. The Z-scores in the _segments.bed file are generally much more reliable

**Comment by bnouyou** [comment]
Hum, in 'segments.bed', these are the zscores for the sample compared to the calculated reference ?
What if there is nothing reported for a position in 'segments.bed' ? Does it mean that there is no aberration at this position for the sample ?

To explain my case : on one sample I know I have a deletion (I have done aCGH). When I look in 'segments.bed', there is nothing reported for this chromosome at this position. But if I look in 'bins.bed', I see consecutive bins with zscores like -10. If I look for the start and stop of these bins, it corresponds to the known deletion. That's why I would like to understand why it's not reported as aberration ?

**Comment by leraman** [comment]
Is it possible that is it not recognized as a separate segment? In that case, an aberration will never be called. You could try to lower `--alpha` to, e.g., 0.1.

**Comment by bnouyou** [comment]
Hello,
I have tried and the result is the same. Before, I used the default value.
What is the impact of the change of the `--alpha` parameter ?
