### ISSUE TITLE
Question about z-score cutoff

### ISSUE THREAD

**Issue by KhanhLPBao** [CenterForMedicalGeneticsGhent/WisecondorX#74]
Hi, on the article about Wisecondor I found that the bin is called for abbreviation when abs(z-score) is more than 3. However, the default setting on WisecondorX shows the z-score cutoff is 5. Does this zscore cutoff is the same z-score used on the Wisecondor article or the different?

**Comment by leraman** [comment]
The score is the same, the default cutoff however changed to 5, which is more robust
