### ISSUE TITLE
Sex determination

### ISSUE THREAD

**Issue by smruti241** [CenterForMedicalGeneticsGhent/WisecondorX#81]
I am using WisecondorX and ot is working perfectly. I just want to clarify, I am running wisecondorX gender command and it is giving correct gender in most of the times, but it depends upon the reference npz files. I want to know if it is giving perfectly correct gender or I need to identify using other tools or algorthim also? Secondly, it is mentioned that atleast 50 reference samples or healthy samples we need for reference, if it is 50 healthy samples, then it will give correct gender for every individual sample? What if I have fetal fraction and it says the sample is female and wisecondorX gender gave male, then what should I do?

**Comment by leraman** [comment]
Based on your other comments, I'm assuming you use wisecondorx for NIPT? The gender determination algorithm in WisecondorX is not the best for determining the fetal gender. To best determine the fetal gender you should use some custom scripting (like in the PREFACE paper) or use another tool.

**Comment by smruti241** [comment]
But for preface, we need config file which has all samples, fetal fraction and gender, then what's the use of preface? If I have unknown samples, then how can I know how to create config file. I am not a wet lab person, so I don't know whether NIPT wet lab procedure gives gender or not. But what if I have only NIPT files and I have to determine the gender?
