### ISSUE TITLE
μw meaning in calculation of segmental z-score.

### ISSUE THREAD

**Issue by chesterlee7246** [CenterForMedicalGeneticsGhent/WisecondorX#86]
Hello, author, I am reading your article 《WisecondorX: improved copy number detection for routine shallow whole-genome sequencing》. I don't understand the segmental z-score calculation method. I hope to get a more detailed explanation.

**Comment by chesterlee7246** [comment]
![image](https://user-images.githubusercontent.com/36124580/143523360-7887c08e-67aa-4fd7-95ed-7c1cfafceb34.png)

**Comment by matthdsm** [comment]
ping @leraman

**Comment by lennartraman** [comment]
Hi @chesterlee7246 

Z-scores are calculated as: `Z = (value - mean) / sd`. Here:

- 'Value' is the weighted mean log2 ratio of a segment in the sample of interest
- 'Mean' is the average of all 'values' (calculated as above) of the samples in the reference
- 'Sd' is the standard deviation of all 'values' (calculated as above) of the samples in the reference

Hope this helps

**Comment by matthdsm** [comment]
Thanks for chiming in Lennart!
