### ISSUE TITLE
cutoffs for gain and loss

### ISSUE THREAD

**Issue by asaki1986** [CenterForMedicalGeneticsGhent/WisecondorX#87]
Hi,

Many thanks for developing such a great tool to analyze the sWGS data.

Rather than NIPT data, we are focusing on the sWGS data from germline blood samples.

Obviously, Z-SCORE of 3 is pre-defined for fetal samples.

Any suggestions for z-score parameter tuning, since the program still output a gain or loss even z-score was set to 7.

![image](https://user-images.githubusercontent.com/32200012/144734674-2e3ed194-3012-446a-a396-26dd6ab1c592.png)

**Comment by matthdsm** [comment]
Hi,

You can get the raw segments with log2 ratio's by using the `--bed` flag during the `predict` step.
https://github.com/CenterForMedicalGeneticsGhent/WisecondorX#stage-3-predict-copy-number-alterations

Cheers
M

**Comment by asaki1986** [comment]
> Hi,
> 
> You can get the raw segments with log2 ratio's by using the `--bed` flag during the `predict` step. https://github.com/CenterForMedicalGeneticsGhent/WisecondorX#stage-3-predict-copy-number-alterations
> 
> Cheers M

Thanks,

Sure I can get the raw log2ratio using --bed flag.

So you suggest using raw log2ratio to predict the CNA region other than z score?
