### ISSUE TITLE
Fetal fraction

### ISSUE THREAD

**Issue by RaraykinValery** [CenterForMedicalGeneticsGhent/WisecondorX#88]
Hello! Could you please tell, is there output file of WiseconderX, where I can find calculated percent of fetal fraction?

**Comment by matthdsm** [comment]
Hi,

There's no direct measure of fetal fraction. You can however estimate the fetal fraction for chrY using this [gist](https://gist.github.com/matthdsm/f5657f048871ea16b7d0df9e8d39d362)

M
