### ISSUE TITLE
Add sample name in plots as title (optionally)

### ISSUE THREAD

**Issue by lbeltrame** [CenterForMedicalGeneticsGhent/WisecondorX#92]
This is very useful if you have a lot of samples to evaluate.

**Comment by matthdsm** [comment]
Hi Luca,

WisecondorX is currently not being actively developed ( should resume shortly), but we welcome pull requests!

**Comment by lbeltrame** [comment]
Should be easy enough (famous last words!). I'll take a look.

**Comment by lbeltrame** [comment]
Would this warrant a minor version bump so that places like bioconda can pick it up, and in turn I do not need to make a new image for my pipelines (as I leech off biocontainers ;)?
If not that's fine and I'll patch locally.
