### ISSUE TITLE
RFE: Set random seed for CBS

### ISSUE THREAD

**Issue by lbeltrame** [CenterForMedicalGeneticsGhent/WisecondorX#96]
DNAcopy uses permutations during segmentation, which means that results are non-deterministic. In our specific applications, though, where we need precision for CPA, for example, this randomness can affect the results.

A good idea would be the possibility set a seed at the beginning of CBS so that at least reproducibility is somehow guaranteed. For backwards compatibility, such an option would need to be *off*.

I'm willing to do the work myself if this is deemed a worthwhile addition.

**Comment by leonorpalmeira** [comment]
Dear WisecondorX team, this issue is also biting us. We have done some reproducibility tests for our validation and there are some important CNVs from our validation dataset that only get identified once in a while on the exact same dataset with all identical invocation parameters. It would be very handy to us as well if we can at least fix the seed to have reproducible results.

**Comment by leonorpalmeira** [comment]
I have tested this locally and adding `set.seed(MyArbitraryValue)` just before calling the `segment()` function from `DNAcopy` in `wisecondorX/include/CBS.R` fixes the reproducibility issue:

```R
set.seed(97)
 CNA.object <- CNA(for.cbs$y, for.cbs$chromosome, for.cbs$x, data.type = "logratio", sampleid = "X")
 f = file()
 sink(file=f) ## silence output
CNA.object <- invisible(segment(CNA.object, alpha = as.numeric(alpha), verbose=1, weights=weights[cbs.mask])$output)
sink() ## undo silencing
close(f)
```

**Comment by matthdsm** [comment]
Hi all

Apologies for the radio silence. I'm slowly getting a bit more room to work on this again.
I've opened a branch with a tentative fix for this. https://github.com/CenterForMedicalGeneticsGhent/WisecondorX/tree/bug/96

Can you check it out and report back?

Thanks
Matthias

**Comment by leonorpalmeira** [comment]
Dear Matthias,

the code in the MR looks good to me, thanks a lot for looking into this!

Best
Leonor
