### ISSUE TITLE
wisecondorX ValueError: The requested array has an inhomogeneous shape after 1 dimensions

### ISSUE THREAD

**Issue by xuanblo** [CenterForMedicalGeneticsGhent/WisecondorX#99]
wisecondorX/main.py", line 220, in tool_test
null_ratios = np.array(
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (142030,) + inhomogeneous part.

**Comment by liuhepkk** [comment]
> 

I met the same problem which can be simplely solved by change the wisecondorX/main.py in line 221 like below, and it worked. U can try~ 

 before: [x.tolist() for x in null_ratios_aut_per_bin] + [x.tolist() for x in null_ratios_gon_per_bin])
 after  :       ([x.tolist() for x in null_ratios_aut_per_bin] + [x.tolist() for x in null_ratios_gon_per_bin]),dtype=object)

**Comment by arshah18** [comment]
> > 
> 
> I met the same problem which can be simplely solved by change the wisecondorX/main.py in line 221 like below, and it worked. U can try~
> 
> before: [x.tolist() for x in null_ratios_aut_per_bin] + [x.tolist() for x in null_ratios_gon_per_bin]) after : ([x.tolist() for x in null_ratios_aut_per_bin] + [x.tolist() for x in null_ratios_gon_per_bin]),dtype=object)

I had a similar issue and your fix solved it, thanks! --Ab,

**Comment by matthdsm** [comment]
Thanks for the fix! This issue has been resolved in the latest `dev` version
